[book]
authors = ["mbrg"]
language = "en"
src = "docs"
title = "Agent Security & Observability Protocol"

[build]
build-dir = "book"

[output.html]
edit-url-template = "https://github.com/zenitysec/AOS/edit/main/{path}"
fold.enable = true
git-repository-url = "https://github.com/zenitysec/AOS"