site_name: Agent Observability Standard
site_url: !ENV GITHUB_PAGES_URL
site_description: >-
  An industry standard for building trustworthy AI agents - inspectable, observable and instrumentable
   to enable enterprise-wide adoption with confidence.

# Repository
repo_name: zenitysec/aos
repo_url: https://github.com/zenitysec/aos

# Copyright
copyright: Copyright &copy; 2025 AOS

docs_dir: docs

theme:
  name: material
  features:
    - search.suggest
    # edit this page for each doc page
    - content.action.edit
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono
  favicon: material/security
  icon: 
    logo: material/security

plugins:
  - search
  # - mike:
  #     alias_type: symlink
  #     redirect_template: null
  #     deploy_prefix: ''
  #     canonical_version: null
  #     version_selector: true
  #     css_dir: css
  #     javascript_dir: js

# Additional configuration
extra:
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  social:
    - icon: /fontawesome/regular/envelope
      name: Send us an email
      link: mailto:aos@zenity.io
  # version:
  #   provider: mike

nav:
  - Trustworthy Agents: README.md
  - AOS: aos.md
  - Topics:
    - Core concepts: topics/core_concepts.md
    - AOS in Action: topics/AOS_in_action_example.md
    - Extensions:
      - Extend A2A: topics/extensions/extend_a2a.md
      - Extend MCP: topics/extensions/extend_mcp.md
  - Tools:
    - Guardian Agent:
      - Overview: tools/guardian_agent/README.md
      - Apply Corporate Policy: tools/guardian_agent/apply_corporate_policy.md
      - Block Data Leakage: tools/guardian_agent/block_data_leakage.md
      - Generate Audit Log: tools/guardian_agent/generate_audit_log.md
      - Generate SBOM: tools/guardian_agent/generate_sbom.md
    - Native Support: tools/native_support/README.md
  - Specification:
    - Inspect:
      - Overview: spec/AgBOM/README.md
      - Extend CycloneDX: spec/AgBOM/extend_cyclonedx.md
      - Extend SPDX: spec/AgBOM/extend_spdx.md
      - Extend SWID: spec/AgBOM/extend_swid.md
    - Audit:
      - Overview: spec/Observability/README.md
      - OpenTelemetry: spec/Observability/OpenTelemetry.md
      - OCSF:
        - Overview: spec/Observability/OCSF/README.md
        - Implementation Examples: spec/Observability/OCSF/implementation_examples.md
    - Instrument:
      - Overview: spec/ASOP/README.md
      - ASOP specification: spec/ASOP/specification.md
  - About: about.md

markdown_extensions:
  # Emojis
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  # Syntax Highlighting
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  # Callouts
  - admonition
  - pymdownx.details
