[project]
name = "aos"
version = "0.1.0"
description = "AOS Documentation"
requires-python = ">=3.8"

dependencies = [
    "mike>=1.2.0",
    "mkdocs-material>=9.6.14",
    "pymdown-extensions>=10.0.0"
]